
# 0. Read me --------------------------------------

## Script generated by 
## Konstantina Nasiou (sections 1., 2., 3., 4., 5.)
## Konstantina Zografou (section 3.)
## Apostolis Stefanidis (section 3.)
##
## for the study titled:
## Environmental and seasonal filtering of taxonomic, functional, and phylogenetic diversity patterns
## of mountain butterflies in a Prime Butterfly Area, Greece
##
## Authors:
## Konstantina Nasiou [BAT], Konstantina Zografou [BAT], Andreja Radović [RBI],
## Apostolis Stefanidis [BAT], Vassiliki Kati [BAT]
## 
## [BAT] Department of Biological Applications and Technology, University of Ioannina, Ioannina, Greece
## [RBI] Ruđer Bošković Institute, Division of Marine and Environmental Research,
##       Laboratory for Informatics and Environmental Modelling, Zagreb, Croatia
##
## Questions:
## (1) What is the value of the two mountains for butterfly conservation?
## (2) Are butterfly communities in forest clearings different from those in mountainous grasslands?
## (3) How is seasonality affecting butterfly communities and their diversity patterns? 
## (4) Do taxonomic, functional and phylogenetic diversity spatially covary? 
## (5) What are the effects of habitat variables on alpha diversity metrics and community composition? 
## (6) How do habitat-trait interactions influence species abundances? 
##
## 
##
## To run the code, replace the dataset paths with the actual file paths on your computer.


# 1. Sampling efficiency and indices --------------------------------------

#Load packages
library(vegan)       
library(fossil)      
library(FD)          
library(ape)         
library(picante)     
library(phyloregion) 


# 1.1 Sampling efficiency -------------------------------------------------
#Load dataset
abund <- read.table("Species abundance.csv", sep=",", header=T)

#Keep only numeric species columns
sp <- abund[, sapply(abund, is.numeric)]
sp[is.na(sp)] <- 0

# Total pooled Chao1 
total_abund <- matrix(colSums(sp), nrow = 1) # 1 row = pooled community
chao_total <- chao1(total_abund, taxa.row = FALSE)
chao_total

#Rarefraction
sp_accum <- specaccum(sp, method = "random")
plot(sp_accum, 
     col = "blue",
     ci.type = "poly",
     ci.col = adjustcolor("blue", 0.2),
     xlab = "Sampling units (sites)",
     ylab = "Species richness",
     main = "Sample-based rarefaction")

# 1.2 Functional indices --------------------------------------------------
#Load the datasets
traits <- read.table("Trait_variables.csv", sep=",", header=T)
abund <- read.table("Species abundance.csv", sep=",", header=T)


# Set row names for datasets
rownames(abund) = abund[, 1]; abund <- abund[, -1]
rownames(traits) = traits$Species
traits = traits[, -which(names(traits) == "Species")]

# Check if row names match column names 
all(rownames(traits) %in% colnames(abund))
all(colnames(abund) %in% rownames(traits))
row_missing <- setdiff(rownames(traits), colnames(abund))
col_missing <- setdiff(colnames(abund), rownames(traits))

# Print the mismatches
row_missing
col_missing


traits <- as.matrix(traits)
abund <- as.matrix(abund)
sapply(traits, is.numeric)
sapply(abund, is.numeric)

#Calculate functional diversity indices
results <- dbFD(traits, abund)
print(results)

#Visualizing the indices 
barplot(results$FRic, main = "Functional Richness", ylab = "FRic")
barplot(results$FEve, main = "Functional Eveness", ylab = "FEve")
barplot(results$FDiv, main = "Functional Diversity", ylab = "FDiv")
barplot(results$FDis, main = "Functional Dispersion", ylab = "FDis")
barplot(results$RaoQ, main = "Rao’s Quadratic Entropy", ylab = "RaoQ")



# 1.3 Phylogenetic indices ------------------------------------------------

#Load the phylogenetic tree 
phylo_tree <- read.tree("EUROPEAN_BUTTERFLIES_FULLMCC_DROPTIPED.nwk")
print(phylo_tree)
print(phylo_tree$tip.label)
plot(phylo_tree)
str(phylo_tree)

#Create my own phyl. tree 
#Subset and load species list
species_list <- read.csv("Species_list.csv")

# Extract species names as a vector
species_names <- species_list$Species
print(species_names)

# Ensure all species in the list are in the phylogenetic tree
species_to_keep <- species_names[species_names %in% phylo_tree$tip.label]

# Subset the phylogenetic tree to keep only the species list
my_tree <- drop.tip(phylo_tree, setdiff(phylo_tree$tip.label, species_to_keep))

missing_species <- setdiff(species_names, phylo_tree$tip.label)
if (length(missing_species) > 0) {
  cat("Warning: These species are not in the phylogenetic tree:\n")
  print(missing_species)
}


#Plot
plot(my_tree)
title("My Phylogenetic Tree")
str(phylo_tree)

plot(my_tree, type = "fan", cex = 0.6) #### circular layout
title("Circular Phylogenetic Tree")


#Load community data 
comm= read.table("Species abundance.csv", sep=",", header=T)
str(comm)
print(comm)
rownames(comm) = comm[, 1]; comm <- comm[, -1]

#Direct replacement of the species 
colnames(comm)[colnames(comm) == "Satyrium_w.album"] <- "Satyrium_w-album"

My_Tree <- match.phylo.comm(phy = my_tree, 
                            comm = comm)$phy
CleanComm <- match.phylo.comm(phy = my_tree, 
                              comm = comm)$comm
#No species was excluded this time, the tree still includes all 80 species

str(My_Tree)
plot(My_Tree,
     cex = 0.4)


#Phylogenetic diversity
PD <- pd(samp = CleanComm, 
         tree = My_Tree,
         include.root = FALSE)
print(PD)

#PD - SR
cor.test(PD$PD, PD$SR)

#Visualize
plot(PD$PD, 
     PD$SR, 
     xlab = "Phylogenetic Diversity", ylab = "Species Richness", 
     pch = 16)

#Standardized effect sizes of PD 
ses.pd <- ses.pd(samp = CleanComm, 
                 tree = My_Tree, 
                 null.model = "taxa.labels", 
                 runs = 1000)
print(ses.pd)


# Create a matrix of cophenetic distances among taxa
cophenDist <- cophenetic.phylo(My_Tree)
print(cophenDist)

# Standardized Effect Size of the MPD
ses.mpd <- ses.mpd(CleanComm, 
                   cophenDist, 
                   null.model = "taxa.labels", 
                   abundance.weighted = FALSE, 
                   runs = 100)
head(ses.mpd)

# Calculate Net Relatedness Index
NRI <- as.matrix(-1 * 
                   ((ses.mpd[,2] - ses.mpd[,3]) /
                      ses.mpd[,4]))
rownames(NRI) <- row.names(ses.mpd)
colnames(NRI) <- "NRI"

print(NRI)


#Phylogenetic endemism 

CleanComm_mat <- as.matrix(CleanComm)
PE <- phylo_endemism(CleanComm_mat, My_Tree, weighted = TRUE)
print(PE)

# 2. Comparative analyses -------------------------------------------------

# 2.A Mountain -------------------------------------------------------------

#Load packages
library(vegan)        
library(fossil)        
library(indicspecies)  
library(ggplot2)       
library(dplyr)         
library(pairwiseAdonis) 


# 2.A.1 Rarefraction ------------------------------------------------
#Load dataset
mount <- read.table("matrix_mount.csv", sep=",", header=TRUE)

grp <- factor(mount$Group)   
sp  <- mount[, -(1:2)]      
sp_T <- sp[grp == "T", ]
sp_S <- sp[grp == "S", ]

# species rarefaction
accum_T <- specaccum(sp_T, method = "random")
accum_S <- specaccum(sp_S, method = "random")

plot(accum_T, col="blue", ci.type="poly", ci.col=adjustcolor("blue", 0.2))
plot(accum_S, add=TRUE, col="red", ci.type="poly", ci.col=adjustcolor("red", 0.2))
legend("bottomright", legend=c("F", "G"), col=c("blue", "red"), lty=1, bty="n")

# Chao1 
T_pool <- matrix(colSums(sp_T), nrow = 1)
S_pool <- matrix(colSums(sp_S), nrow = 1)

chao_T <- chao1(T_pool, taxa.row = FALSE)
chao_S <- chao1(S_pool, taxa.row = FALSE)

chao_T
chao_S


# 2.A.2 Mann–Whitney test ------------------------------------------------------------------
#Load dataset
df <- read.table("S_T.csv", sep=",", header=TRUE)
str(df)

num_vars <- names(df)[sapply(df, is.numeric)]
results <- sapply(num_vars, function(v) {
  test <- wilcox.test(df[[v]] ~ df$Group)
  c(W = test$statistic, p.value = test$p.value)
})

results_df <- as.data.frame(t(results))

#Add BH-adjusted p-values
results_df$p.value <- as.numeric(results_df$p.value)
results_df$p.BH <- p.adjust(results_df$p.value, method = "BH")

results_df <- results_df[order(results_df$p.value), ]
results_df


# 2.A.3 NMDS --------------------------------------------------------------
com = mount[,3:ncol(mount)]
dist_matrix <- vegdist(com, method = "bray")
set.seed(999)
nmds <- metaMDS(dist_matrix, k = 2, trymax = 100, autotransform = FALSE)
nmds

plot(nmds)
class(nmds)
print(scores(nmds))

#plot
ord <- as.data.frame(scores(nmds, display = "sites"))
ord$Group <- mount$Group

ggplot(ord, aes(x = NMDS1, y = NMDS2, color = Group, fill = Group, shape = Group)) +
  stat_ellipse(aes(group = Group), type = "norm", level = 0.68,
               geom = "polygon", alpha = 0.18, linewidth = 0.8) +
  stat_ellipse(aes(group = Group), type = "norm", level = 0.68,
               geom = "path", linewidth = 0.8) +
  geom_point(size = 3, alpha = 0.9) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        legend.title = element_text(size = 11)) +
  labs(title = "NMDS — Community composition in forest clearings vs grasslands",
       x = "NMDS1", y = "NMDS2")



# 2.A.4 PERMANOVA ---------------------------------------------------------

pairwise.adonis2(dist_matrix ~ Group, data = mount, permutations = 999)

#Test for homogeneity of multivariate dispersions
bd <- betadisper(dist_matrix, mount$Group)
bd
anova(bd)         # tests if dispersions differ significantly between S and T
permutest(bd, permutations = 9999)  
plot(bd)

# 2.A.5 Indicator species -------------------------------------------------
#Load dataset
mount <- read.table("matrix_mount.csv", sep=",", header=TRUE)

set.seed(123)
indval <- multipatt(com, mount$Group, func = "IndVal.g", duleg = TRUE, control = how(nperm = 9999))
summary(indval)

#print A (specificity) and B (fidelity) 
summary(indval, indvalcomp = TRUE)



# 2.B Habitat -------------------------------------------------------------

#Load packages
library(vegan)        
library(fossil)        
library(indicspecies)  
library(ggplot2)       
library(dplyr)         
library(pairwiseAdonis) 


# 2.B.1 Rarefraction ------------------------------------------------
#Load dataset
hab <- read.table("matrix_hab.csv", sep=",", header=TRUE)

grp <- factor(hab$Group)   
sp  <- hab[, -(1:2)]      
sp_F <- sp[grp == "F", ]
sp_G <- sp[grp == "G", ]

# species rarefaction
accum_F <- specaccum(sp_F, method = "random")
accum_G <- specaccum(sp_G, method = "random")

plot(accum_F, col="blue", ci.type="poly", ci.col=adjustcolor("blue", 0.2))
plot(accum_G, add=TRUE, col="red", ci.type="poly", ci.col=adjustcolor("red", 0.2))
legend("bottomright", legend=c("F", "G"), col=c("blue", "red"), lty=1, bty="n")

# Chao1 
F_pool <- matrix(colSums(sp_F), nrow = 1)
G_pool <- matrix(colSums(sp_G), nrow = 1)

chao_F <- chao1(F_pool, taxa.row = FALSE)
chao_G <- chao1(G_pool, taxa.row = FALSE)

chao_F
chao_G


# 2.B.2 Mann–Whitney test ------------------------------------------------------------------
#Load dataset
df <- read.table("G_T.csv", sep=",", header=TRUE)
str(df)

num_vars <- names(df)[sapply(df, is.numeric)]
results <- sapply(num_vars, function(v) {
  test <- wilcox.test(df[[v]] ~ df$Group)
  c(W = test$statistic, p.value = test$p.value)
})

results_df <- as.data.frame(t(results))

#Add BH-adjusted p-values
results_df$p.value <- as.numeric(results_df$p.value)
results_df$p.BH <- p.adjust(results_df$p.value, method = "BH")

results_df <- results_df[order(results_df$p.value), ]
results_df


# 2.B.3 NMDS --------------------------------------------------------------
com = hab[,3:ncol(hab)]
dist_matrix <- vegdist(com, method = "bray")
set.seed(999)
nmds <- metaMDS(dist_matrix, k = 2, trymax = 100, autotransform = FALSE)
nmds

plot(nmds)
class(nmds)
print(scores(nmds))

#plot
ord <- as.data.frame(scores(nmds, display = "sites"))
ord$Group <- hab$Group

ggplot(ord, aes(x = NMDS1, y = NMDS2, color = Group, fill = Group, shape = Group)) +
  stat_ellipse(aes(group = Group), type = "norm", level = 0.68,
               geom = "polygon", alpha = 0.18, linewidth = 0.8) +
  stat_ellipse(aes(group = Group), type = "norm", level = 0.68,
               geom = "path", linewidth = 0.8) +
  geom_point(size = 3, alpha = 0.9) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        legend.title = element_text(size = 11)) +
  labs(title = "NMDS — Community composition in forest clearings vs grasslands",
       x = "NMDS1", y = "NMDS2")



# 2.B.4 PERMANOVA ---------------------------------------------------------

pairwise.adonis2(dist_matrix ~ Group, data = hab, permutations = 999)

#Test for homogeneity of multivariate dispersions
bd <- betadisper(dist_matrix, hab$Group)
bd
anova(bd)         # tests if dispersions differ significantly between F and G
permutest(bd, permutations = 9999)  
plot(bd)


# 2.B.5 Indicator species -------------------------------------------------
#Load dataset
hab <- read.table("matrix_hab.csv", sep=",", header=TRUE)

set.seed(123)
indval <- multipatt(com, hab$Group, func = "IndVal.g", duleg = TRUE, control = how(nperm = 9999))
summary(indval)

#print A (specificity) and B (fidelity) 
summary(indval, indvalcomp = TRUE)



# 2.C Seasonal visits -----------------------------------------------------
#Load packages
library(vegan)          
library(pctax)          
library(fossil)         
library(FD)             
library(ape)            
library(picante)        
library(phyloregion)    
library(dplyr)          
library(tidyr)          
library(rstatix)        
library(readr)          
library(VennDiagram)    
library(UpSetR)         
library(ComplexHeatmap) 
library(pairwiseAdonis) 
library(indicspecies)   
library(coin)

# 2.C.1 Rarefraction ------------------------------------------------------
#Load datasets
visit_a <- read.table("Visit_a.csv", sep=";", header=T)
visit_b <- read.table("Visit_b.csv", sep=";", header=T)
visit_c <- read.table("Visit_c.csv", sep=";", header=T)

rownames(visit_a) <- visit_a[, 1]; visit_a <- visit_a[, -1]
rownames(visit_b) <- visit_b[, 1]; visit_b <- visit_b[, -1]
rownames(visit_c) <- visit_c[, 1]; visit_c <- visit_c[, -1]


#plot
par(mfrow = c(3,2))
rfa <- specaccum(visit_a)
plot(rfa, main = "Basic plot: Visit A")
plot(rfa, ci.type="poly", col="blue", lwd=2, ci.lty=0, ci.col="lightblue", 
     main = "Colored Plot: Visit A")

rfb <- specaccum(visit_b)
plot(rfb, main = "Basic plot: Visit B")
plot(rfb, ci.type="poly", col="blue", lwd=2, ci.lty=0, ci.col="lightblue", 
     main = "Colored Plot: Visit B")

rfc <- specaccum(visit_c)
plot(rfc, main = "Basic plot: Visit C")
plot(rfc, ci.type="poly", col="blue", lwd=2, ci.lty=0, ci.col="lightblue", 
     main = "Colored Plot: Visit C")

#Transpose the matrix and plot
transposed_a <- t(visit_a)
a <- rare_curve_sample(transposed_a)
plot(a)

transposed_b <- t(visit_b)
b <- rare_curve_sample(transposed_b)
plot(b)

transposed_c <- t(visit_c)
c <- rare_curve_sample(transposed_c)
plot(c)


#Chao1

#Load dataset
visits_chao <- read.table("SpeciesxVisits_abund.csv", sep=";", header=T)
rownames(visits_chao) <- visits_chao[, 1]; visits_chao <- visits_chao[, -1]

chao1(visits_chao$Visit_a, taxa.row = TRUE)
chao1(visits_chao$Visit_b, taxa.row = TRUE)
chao1(visits_chao$Visit_c, taxa.row = TRUE)


# 2.C.2 Compute indices per visit -----------------------------------------

# 2.C.2a Shannon index ------------------------------------------------------------------

diversity(visit_a, index="shannon")
diversity(visit_b, index="shannon")
diversity(visit_c, index="shannon")

# 2.C.2b Functional indices ------------------------------------------------------------------

#Load trait dataset
traits <- read.table("Trait_variables.csv", sep=",", header=T)

rownames(traits) = traits$Species
traits = traits[, -which(names(traits) == "Species")]

#Vist A
#align datasets
all(rownames(traits) %in% colnames(visit_a))
all(colnames(visit_a) %in% rownames(traits))
row_missing <- setdiff(rownames(traits), colnames(visit_a))
row_missing

# Remove row names not matching
traits_a <- traits[!rownames(traits) %in% row_missing, ]

# Make them matrices
traits_a <- as.matrix(traits_a)
visit_a <- as.matrix(visit_a)

# Ensure data are numeric
sapply(traits_a, is.numeric)
sapply(visit_a, is.numeric)

results <- dbFD(traits_a, visit_a)
print(results)

#plot
barplot(results$FRic, main = "Functional Richness", ylab = "FRic")
barplot(results$FDis, main = "Functional Dispersion", ylab = "FDis")
barplot(results$RaoQ, main = "Rao’s Quadratic Entropy", ylab = "RaoQ")

#Visit B
#align datasets
all(rownames(traits) %in% colnames(visit_b))
all(colnames(visit_b) %in% rownames(traits))
row_missing <- setdiff(rownames(traits), colnames(visit_b))
row_missing

# Remove row names not matching
traits_b <- traits[!rownames(traits) %in% row_missing, ]

#Make them matrices
traits_b <- as.matrix(traits_b)
visit_b <- as.matrix(visit_b)

# Ensure data are numeric
sapply(traits_b, is.numeric)
sapply(visit_b, is.numeric)


results <- dbFD(traits_b, visit_b)
print(results)

#plot
barplot(results$FRic, main = "Functional Richness", ylab = "FRic")
barplot(results$FDis, main = "Functional Dispersion", ylab = "FDis")
barplot(results$RaoQ, main = "Rao’s Quadratic Entropy", ylab = "RaoQ")


#Visit C
#align datasets
all(rownames(traits) %in% colnames(visit_c))
all(colnames(visit_c) %in% rownames(traits))
row_missing <- setdiff(rownames(traits), colnames(visit_c))
row_missing

# Remove row names not matching
traits_c <- traits[!rownames(traits) %in% row_missing, ]

#Make them matrices
traits_c <- as.matrix(traits_c)
visit_c <- as.matrix(visit_c)

# Ensure data are numeric
sapply(traits_c, is.numeric)
sapply(visit_c, is.numeric)


results <- dbFD(traits_c, visit_c)
print(results)

#plot
barplot(results$FRic, main = "Functional Richness", ylab = "FRic")
barplot(results$FDis, main = "Functional Dispersion", ylab = "FDis")
barplot(results$RaoQ, main = "Rao’s Quadratic Entropy", ylab = "RaoQ")


# 2.C.2c Phylogenetic diversity & Net Relatedness Index  ------------------------------------------------------------------

#Load the phylogenetic tree
phylo_tree <- read.tree("EUROPEAN_BUTTERFLIES_FULLMCC_DROPTIPED.nwk")
print(phylo_tree)
print(phylo_tree$tip.label)
plot(phylo_tree)
str(phylo_tree)

#Subset 
# Load species list
species_list <- read.csv("Species_list.csv")

# Extract species names as a vector
species_names <- species_list$Species
print(species_names)

# Ensure all species in the list are in the phylogenetic tree
species_to_keep <- species_names[species_names %in% phylo_tree$tip.label]

# Subset the phylogenetic tree to keep only species list
my_tree <- drop.tip(phylo_tree, setdiff(phylo_tree$tip.label, species_to_keep))

missing_species <- setdiff(species_names, phylo_tree$tip.label)
if (length(missing_species) > 0) {
  cat("Warning: These species are not in the phylogenetic tree:\n")
  print(missing_species)
}

#Plot 
plot(my_tree)
title("My Phylogenetic Tree")
str(phylo_tree)

#Load community data for each visit
visit_a_p <- read.table("Visit_a_phyl.csv", sep=";", header=T)
visit_b_p <- read.table("Visit_b_phyl.csv", sep=";", header=T)
visit_c_p <- read.table("Visit_c_phyl.csv", sep=";", header=T)

rownames(visit_a_p) <- visit_a_p[, 1]; visit_a_p <- visit_a_p[, -1]
rownames(visit_b_p) <- visit_b_p[, 1]; visit_b_p <- visit_b_p[, -1]
rownames(visit_c_p) <- visit_c_p[, 1]; visit_c_p <- visit_c_p[, -1]

#Make a direct replacement of the species S. w-album
colnames(visit_a_p)[colnames(visit_a_p) == "Satyrium_w.album"] <- "Satyrium_w-album"

#produce a phyl. tree for each visit
My_Tree_a <- match.phylo.comm(phy = my_tree, 
                              comm = visit_a_p)$phy
CleanComm_a <- match.phylo.comm(phy = my_tree, 
                                comm = visit_a_p)$comm

My_Tree_b <- match.phylo.comm(phy = my_tree, 
                              comm = visit_b_p)$phy
CleanComm_b <- match.phylo.comm(phy = my_tree, 
                                comm = visit_b_p)$comm

My_Tree_c <- match.phylo.comm(phy = my_tree, 
                              comm = visit_c_p)$phy
CleanComm_c <- match.phylo.comm(phy = my_tree, 
                                comm = visit_c_p)$comm

#Plot 
plot(My_Tree_a, type = "phylogram", cex = 0.7, no.margin = TRUE)
plot(My_Tree_b, type = "phylogram", cex = 0.7, no.margin = TRUE)
plot(My_Tree_c, type = "phylogram", cex = 0.7, no.margin = TRUE)

#PD & NRI
#Visit A
PDa <- pd(samp = CleanComm_a, 
          tree = My_Tree_a,
          include.root = FALSE)
print(PDa)

cophenDista <- cophenetic.phylo(My_Tree_a)
ses.mpda <- ses.mpd(CleanComm_a, 
                    cophenDista, 
                    null.model = "taxa.labels", 
                    abundance.weighted = FALSE, 
                    runs = 100)
NRIa <- as.matrix(-1 * 
                    ((ses.mpda[,2] - ses.mpda[,3]) /
                       ses.mpda[,4]))
rownames(NRIa) <- row.names(ses.mpda)
colnames(NRIa) <- "NRI"
print(NRIa)

#vISIT B
PDb <- pd(samp = CleanComm_b, 
          tree = My_Tree_b,
          include.root = FALSE)
print(PDb)

cophenDistb <- cophenetic.phylo(My_Tree_b)
ses.mpdb <- ses.mpd(CleanComm_b, 
                    cophenDistb, 
                    null.model = "taxa.labels", 
                    abundance.weighted = FALSE, 
                    runs = 100)
NRIb <- as.matrix(-1 * 
                    ((ses.mpdb[,2] - ses.mpdb[,3]) /
                       ses.mpdb[,4]))
rownames(NRIb) <- row.names(ses.mpdb)
colnames(NRIb) <- "NRI"
print(NRIb)

#Visit c
PDc <- pd(samp = CleanComm_c, 
          tree = My_Tree_c,
          include.root = FALSE)
print(PDc)

cophenDistc <- cophenetic.phylo(My_Tree_c)
ses.mpdc <- ses.mpd(CleanComm_c, 
                    cophenDistc, 
                    null.model = "taxa.labels", 
                    abundance.weighted = FALSE, 
                    runs = 100)
NRIc <- as.matrix(-1 * 
                    ((ses.mpdc[,2] - ses.mpdc[,3]) /
                       ses.mpdc[,4]))
rownames(NRIc) <- row.names(ses.mpdc)
colnames(NRIc) <- "NRI"
print(NRIc)

# 2.C.2d Phylogenetic endemism ------------------------------------------------------------------

#Visit A
class(My_Tree_a)
class(CleanComm_a)
CleanComm_a <- as.matrix(CleanComm_a)
str(CleanComm_a)  

PEa <- phylo_endemism(CleanComm_a, My_Tree_a, weighted = TRUE)
print(PEa)


#Visit B
class(My_Tree_b)
class(CleanComm_b)
CleanComm_b <- as.matrix(CleanComm_b)
str(CleanComm_b)  

PEb <- phylo_endemism(CleanComm_b, My_Tree_b, weighted = TRUE)
print(PEb)

#Visit C
class(My_Tree_c)
class(CleanComm_c)
CleanComm_c <- as.matrix(CleanComm_c)
str(CleanComm_c)  

PEc <- phylo_endemism(CleanComm_c, My_Tree_c, weighted = TRUE)
print(PEc)



# 2.C.3 Friedman test -----------------------------------------------------

#Load dataset
dat <- read.table("friedman.csv", sep=",", header=T)

#Tidy
dat <- dat %>%
  mutate(
    Group = factor(Group, levels = c("A","B","C"))
  ) %>%
  group_by(Sites) %>%                      
  filter(n_distinct(Group) == 3) %>%
  ungroup()

# Remove non-numeric columns
tmp <- dat[, !(names(dat) %in% c("Sites", "Group"))]

# Keep only numeric variables
num_vars <- names(tmp)[sapply(tmp, is.numeric)]

num_vars

long <- dat %>%
  pivot_longer(
    cols = all_of(num_vars),
    names_to = "Variable",
    values_to = "Value"
  ) %>%
  filter(!is.na(Value))

#Loop for Friedman tests per variable 
friedman_results <- long %>%
  group_by(Variable) %>%
  friedman_test(Value ~ Group | Sites) %>%
  ungroup()

#Kendall's W effect size per variable
friedman_effect <- long %>%
  group_by(Variable) %>%
  friedman_effsize(Value ~ Group | Sites) %>%
  ungroup()

#Paired post-hoc Wilcoxon tests (holm) per variable 
posthoc_results <- long %>%
  group_by(Variable) %>%
  pairwise_wilcox_test(
    Value ~ Group,
    paired = TRUE,
    p.adjust.method = "holm",
    id = "Sites"
  ) %>%
  ungroup()


#Pairwise Wilcoxon effect size r per variable

long_safe <- long %>%
  group_by(Variable) %>%
  filter(n_distinct(Value) > 1) %>%
  ungroup()

posthoc_effect <- long_safe %>%
  group_by(Variable) %>%
  wilcox_effsize(
    Value ~ Group,
    paired = TRUE,
    comparisons = list(c("A", "B"), c("A", "C"), c("B", "C"))
  ) %>%
  ungroup()

posthoc_results_with_r <- posthoc_results %>%
  left_join(
    posthoc_effect %>%
      select(Variable, group1, group2, effsize, magnitude),
    by = c("Variable", "group1", "group2")
  ) %>%
  rename(
    r = effsize,
    r_magnitude = magnitude
  )


#Summaries 
friedman_results
friedman_effect
posthoc_results_subset <- posthoc_results[, c("Variable", "group1", "group2", "p", "p.adj", "p.adj.signif")]
posthoc_results_subset

#Export 
write.csv(friedman_results, "friedman_results.csv", row.names = FALSE)
write.csv(friedman_effect,  "friedman_effectsize.csv", row.names = FALSE)
write.csv(posthoc_results,  "posthoc_results.csv", row.names = FALSE)
write.csv(posthoc_results_with_r, "posthoc_results_with_r.csv", row.names = FALSE)

#Compute the median per group
long %>%
  group_by(Variable, Group) %>%
  summarise(Median = median(Value, na.rm = TRUE)) %>%
  arrange(Variable, Group)

#Median + IQR for 
summ_median_iqr <- long %>%
  group_by(Variable, Group) %>%
  summarise(
    n    = sum(!is.na(Value)),
    q1   = quantile(Value, 0.25, na.rm = TRUE),
    median = median(Value, na.rm = TRUE),
    q3   = quantile(Value, 0.75, na.rm = TRUE),
    IQR  = IQR(Value, na.rm = TRUE),
    .groups = "drop"
  )

#binary variables: % of 1s per group
bin_flags <- long %>%
  group_by(Variable) %>%
  summarise(is_binary = all(na.omit(Value) %in% c(0,1)),
            .groups = "drop")

binary_vars <- bin_flags %>% filter(is_binary) %>% pull(Variable)

summ_binary_props <- long %>%
  filter(Variable %in% binary_vars) %>%
  group_by(Variable, Group) %>%
  summarise(
    n_sites   = n_distinct(Sites),
    count_1   = sum(Value == 1, na.rm = TRUE),
    prop_1    = mean(Value, na.rm = TRUE),          
    perc_1    = 100 * prop_1,                       
    .groups = "drop"
  )

#Export
write_csv(summ_median_iqr,  "summary_median_IQR_by_group.csv")
write_csv(summ_binary_props, "summary_binary_proportions_by_group.csv")


# 2.C.4 Venn diagram and upset plots --------------------------------------

#Load dataset
SP <- read.table("Visits_sp.csv", sep=",", header=TRUE)

# Venn Diagram for shared species
venn.plot <- draw.triple.venn(
  area1 = sum(SP$Visit_a),                  
  area2 = sum(SP$Visit_b),                  
  area3 = sum(SP$Visit_c),                  
  n12 = sum(SP$Visit_a & SP$Visit_b),     
  n23 = sum(SP$Visit_b & SP$Visit_c),     
  n13 = sum(SP$Visit_a & SP$Visit_c),     
  n123 = sum(SP$Visit_a & SP$Visit_b & SP$Visit_c), 
  category = c("Visit A", "Visit B", "Visit C"),
  fill = c("blue", "purple", "yellow"),
  alpha = 0.5,
  cex = 1.5,
  cat.cex = 1.2
)


#Upset biplots 

#distinct mode
distinct_1 = make_comb_mat(SP)
distinct_1

#intesect mode
intersect_2 = make_comb_mat(SP, mode = "intersect")
intersect_2

#union mode
union_3 = make_comb_mat(SP, mode = "union")
union_3

#Plot
UpSet(distinct_1)
UpSet(intersect_2)
UpSet(union_3)

# 2.C.5 NMDS --------------------------------------------------------------

#Load dataset
Matrix <- read.table("Matrix.csv", sep=";", header=TRUE)


com = Matrix[,4:ncol(Matrix)]
dist_matrix <- vegdist(com, method = "bray")
set.seed(999)
nmds = metaMDS(com, distance = "bray")
nmds

#Plot nmds 
plot(nmds)
class(nmds)

#extract NMDS scores 
data.scores <- as.data.frame(nmds$points)
data.scores$AA = Matrix$AA
data.scores$Visits = Matrix$Visits
data.scores$Sites = Matrix$Sites
head(data.scores)
colnames(data.scores)


# 2.C.6 PERMANOVA ---------------------------------------------------------

pairwise.adonis2(dist_matrix ~ Visits, data = Matrix, strata = Matrix$AA)
str(com)

#Test for homogeneity of multivariate dispersions
bd <- betadisper(dist_matrix, Matrix$Visits)
bd
anova(bd)    
permutest(bd, permutations = 9999)  
plot(bd)

dist_to_centroid <- bd$distances
group <- Matrix$Visits

pairwise.wilcox.test(dist_to_centroid,  group,  p.adjust.method = "holm")

# 2.C.7 Indicator species -------------------------------------------------

#Include only numeric columns
abund = Matrix[,4:ncol(Matrix)]
visit = Matrix$Visit
inv = multipatt(abund, visit, func = "r.g", control = how(nperm=9999))
summary(inv)
summary(inv, indvalcomp = TRUE, alpha = 1)  # Show details for all groups


# 3. Regression models ----------------------------------------------------

# 3.1 Load required libraries and datasets
library(glmnet)      
library(car)         
library(MuMIn)       
library(DHARMa)      
library(ggplot2) 
library(patchwork)
library(corrplot)
library(MASS)        
library(mgcv)        
library(effectsize)  
library(performance) 
library(rsq)         
library(lme4)      
library(glmmTMB)  


#Response variables tested: 
#Taxonomic diversity: Species richness (SR), Abundance (Abund), Shannon diversity (H)
#Functional diversity: Functional richness (FRic),Functional dispersion (FDis), Rao’s quadratic entropy (RaoQ)
#Phylogenetic diversity: Phylogenetic diversity (PD), Net Relatedness Index (NRI), Phylogenetic endemism (PE)
#Here, only the response variables with statistically significant relationships
#with the predictors are presented.


var = read.table("Variables.csv", sep=",", header=T)


# 3.1 data exploration ----------------------------------------------------

res_vars <- c("SR", "Abund", "Fric", "PD", "PE")

pre_vars  <- c("Elev", "Slope", "Aheight","Flower", "Veg", "Shrubs", "Soil", "Stones", "Litter" , "Sheight")

plot_list <- list()

for (x in res_vars) {
  for (y in pre_vars) {
    
    p <- ggplot(var, aes_string(x = x, y = y)) +
      geom_point(size = 1.7, alpha = 0.8) +
      geom_smooth(method = "lm", se = FALSE, color = "red", linewidth = 0.8) +
      labs(x = x, y = y, title = paste(y, "vs", x)) +
      theme_minimal(base_size = 10)
    
    plot_list[[paste(x, y, sep = "_")]] <- p
  }
}

# Combine into a grid 
full_grid <- wrap_plots(plot_list, ncol = length(pre_vars))

full_grid


rownames(var) = var[, 1]; var <- var[, -1]
numeric <- var[, sapply(var, is.numeric)]
str(numeric)


# 3.2 Spearman correlations -----------------------------------------------

spearman_matrix <- cor(numeric, method = "spearman", use = "pairwise.complete.obs")
pval_matrix <- matrix(NA, ncol(numeric), ncol(numeric))
rownames(pval_matrix) <- colnames(numeric)
colnames(pval_matrix) <- colnames(numeric)

# Loop through each pair of columns
for (i in 1:ncol(numeric)) {
  for (j in i:ncol(numeric)) {
    valid_rows <- complete.cases(numeric[, c(i, j)])
    test <- cor.test(numeric[valid_rows, i], numeric[valid_rows, j], method = "spearman", exact = FALSE)
    pval_matrix[i, j] <- test$p.value
    pval_matrix[j, i] <- test$p.value  
  }
}


corrplot(spearman_matrix, method = "color", type = "upper", tl.cex = 0.6)

# Set significance level 
alpha <- 0.05
significant_correlations <- pval_matrix < alpha

# Extract the specific pairs that are significant:
significant_pairs <- which(significant_correlations, arr.ind = TRUE)

# View the significant pairs along with their correlation coefficients and p-values
significant_info <- data.frame(
  Var1 = colnames(spearman_matrix)[significant_pairs[, 1]],
  Var2 = colnames(spearman_matrix)[significant_pairs[, 2]],
  Correlation = spearman_matrix[significant_pairs],
  P_value = pval_matrix[significant_pairs]
)

print(significant_info)

# 3.3 VIF and outliers ---------------------------------------------------------------------

var <- as.data.frame(var)

model1l <- lm(SR ~ Elev + Slope + Aheight + Flower + Veg + Shrubs + Soil + Stones + Litter,  data = var)
model2l <- lm(Abund ~ Elev + Slope + Aheight + Flower + Veg + Shrubs + Soil + Stones + Litter, data = var)
model3l <- lm(Fric ~ Elev + Slope + Aheight + Flower + Veg + Shrubs + Soil + Stones + Litter,  data = var)
model4l <- lm(PD ~ Elev + Slope + Aheight + Flower + Veg + Shrubs + Soil + Stones + Litter,  data = var)
model5l <- lm(PE ~ Elev + Slope + Aheight + Flower + Veg + Shrubs + Soil + Stones + Litter, data = var)

vif1 <- vif(model1l)
vif2 <- vif(model2l)
vif3 <- vif(model3l)
vif4 <- vif(model4l)
vif5 <- vif(model5l)

print(vif1)
print(vif2)
print(vif3)
print(vif4)
print(vif5)


# Assign again the models with the variables that have VIF< 5
model1l <- lm(SR ~ Elev + Slope + Aheight + Flower, data = var)
model2l <- lm(Abund ~ Elev + Slope + Aheight + Flower, data = var)
model3l <- lm(Fric ~ Elev + Slope + Aheight + Flower, data = var)
model4l <- lm(PD ~ Elev + Slope + Aheight + Flower, data = var)
model5l <- lm(PE ~ Elev + Slope + Aheight + Flower, data = var)

# Compute Cook's distance
cooks_dist1 <- cooks.distance(model1l)
cooks_dist2 <- cooks.distance(model2l)
cooks_dist3 <- cooks.distance(model3l)
cooks_dist4 <- cooks.distance(model4l)
cooks_dist5 <- cooks.distance(model5l)

# Plot Cook's distance
plot(cooks_dist1, type = "h", main = "Cook's Distance", ylab = "Cook's Distance")
plot(cooks_dist2, type = "h", main = "Cook's Distance", ylab = "Cook's Distance")
plot(cooks_dist3, type = "h", main = "Cook's Distance", ylab = "Cook's Distance")
plot(cooks_dist4, type = "h", main = "Cook's Distance", ylab = "Cook's Distance")
plot(cooks_dist5, type = "h", main = "Cook's Distance", ylab = "Cook's Distance")

#scaling
vars_to_scale <- c("Elev", "Slope", "Aheight", "Flower")

var[vars_to_scale] <- scale(var[vars_to_scale])



# 3.4 Family selection ----------------------------------------------------

model1p <- glm(SR ~ Elev + Slope + Aheight + Flower, family=poisson, data = var)
model2p <- glm(Abund ~ Elev + Slope + Aheight + Flower , family=poisson, data = var)
model1n <- glm.nb(SR ~ Elev + Slope + Aheight + Flower ,  data = var)
model2n <- glm.nb(Abund ~ Elev + Slope + Aheight + Flower , data = var)

model3g <- glm(Fric ~ Elev + Slope + Aheight + Flower, family = Gamma(link="log"), data = var)
model4g <- glm(PD ~ Elev + Slope + Aheight + Flower , family = Gamma(link="log"), data = var)
model5g <- glm(PE ~ Elev + Slope + Aheight + Flower , family = Gamma(link="log"), data = var)


AIC(model1p, model1n)
AIC(model2p, model2n)

anova(model1p, model1n)
anova(model2p, model2n)

# Simulate residuals
sim_SRp <- simulateResiduals(model1p, n = 1000)
sim_SRn <- simulateResiduals(model1n, n = 1000)
sim_Ap <- simulateResiduals(model2p, n = 1000)
sim_An <- simulateResiduals(model2n, n = 1000)
sim_F <- simulateResiduals(model3g, n = 1000)
sim_PD <- simulateResiduals(model4g, n = 1000)
sim_PE <- simulateResiduals(model5g, n = 1000)


# 1) General diagnostic plots
plot(sim_SRp)  
plot(sim_SRn)
plot(sim_Ap)
plot(sim_An)
plot(sim_F)
plot(sim_PD)
plot(sim_PE)

# 2) Tests
testDispersion(sim_SRp)       
testUniformity(sim_SRp)       
testDispersion(sim_An)       
testUniformity(sim_An)       
testDispersion(sim_F)       
testUniformity(sim_F)
testDispersion(sim_PD)       
testUniformity(sim_PD)
testDispersion(sim_PE)       
testUniformity(sim_PE)


# 3) Spatial autocorrelation 
testSpatialAutocorrelation(sim_SRp,  x = var$long,  y = var$lat)
testSpatialAutocorrelation(sim_An,  x = var$long,  y = var$lat)
testSpatialAutocorrelation(sim_F,  x = var$long,  y = var$lat)
testSpatialAutocorrelation(sim_PD,  x = var$long,  y = var$lat)
testSpatialAutocorrelation(sim_PE,  x = var$long,  y = var$lat)

# 3.5 Alternative model structures ----------------------------------------------------------


# 3.5.1 Habitat and Mountain ----------------------------------------------

model1p1 <- glm(SR ~ Elev + Slope + Aheight + Flower ,  family = poisson, data = var)
model1p2 <- glm(SR ~ Elev + Slope + Aheight + Flower + Hab + Mount ,  family = poisson,  data = var)
summary(model1p1)
summary(model1p2)
AIC(model1p1, model1p2)
anova(model1p1, model1p2, test="Chisq")


model2n1 <- glm.nb(Abund ~ Elev + Slope + Aheight + Flower ,data = var)
model2n2 <- glm.nb(Abund ~ Elev + Slope + Aheight + Flower + Hab + Mount ,  data = var)
summary(model2n1)
summary(model2n2)
AIC(model2n1, model2n2)
anova(model2n1, model2n2,test="Chisq" )


model3g1 <- glm(Fric ~ Elev + Slope + Aheight + Flower, family = Gamma(link="log"), data = var)
model3g2 <- glm(Fric ~ Elev + Slope + Aheight + Flower + Hab + Mount, family = Gamma(link="log"), data = var)
summary(model3g1)
summary(model3g2)
AIC(model3g1, model3g2)
anova(model3g1, model3g2 ,test="Chisq" )

model4g1 <- glm(PD ~ Elev + Slope + Aheight + Flower , family = Gamma(link="log"), data = var)
model4g2 <- glm(PD ~ Elev + Slope + Aheight + Flower + Hab + Mount, family = Gamma(link="log"), data = var)
summary(model4g1)
summary(model4g2)
AIC(model4g1, model4g2)
anova(model4g1, model4g2 ,test="Chisq" )

model5g1 <- glm(PE ~ Elev + Slope + Aheight + Flower , family = Gamma(link="log"), data = var)
model5g2 <- glm(PE ~ Elev + Slope + Aheight + Flower + Hab + Mount, family = Gamma(link="log"), data = var)
summary(model5g1)
summary(model5g2)
AIC(model5g1, model5g2)
anova(model5g1, model5g2 ,test="Chisq" )


# 3.5.2 Generalized linear models versus Generalized mixed linear models  -------------------------------------------------

var = read.table("Variables.csv", sep=",", header=T)

#scaling
vars_to_scale <- c("Elev", "Slope", "Aheight", "Flower")

var[vars_to_scale] <- scale(var[vars_to_scale])

# site as a factor
var$Code <- as.factor(var$Code)


SR_glm <- glmmTMB(SR ~ Elev + Slope + Aheight + Flower, family = poisson, data = var)
SR_glmm <- glmmTMB(SR ~ Elev + Slope + Aheight + Flower + (1|Code), family = poisson, data = var)
anova(SR_glm, SR_glmm)   
AIC(SR_glm, SR_glmm)


A_glm <- glmmTMB(Abund ~ Elev + Slope + Aheight + Flower, family = nbinom2, data = var)
A_glmm <- glmmTMB(Abund ~ Elev + Slope + Aheight + Flower + (1|Code), family = nbinom2, data = var)
anova(A_glm, A_glmm)   
AIC(A_glm, A_glmm)


Fric_glm <- glmmTMB(Fric ~ Elev + Slope + Aheight + Flower, family = Gamma(link = "log"), data = var)
Fric_glmm <- glmmTMB(Fric ~ Elev + Slope + Aheight + Flower + (1|Code), family = Gamma(link = "log"), data = var)
anova(Fric_glm, Fric_glmm)  
AIC(Fric_glm, Fric_glmm)


PD_glm  <- glmmTMB(PD ~ Elev + Slope + Aheight + Flower, family = Gamma(link = "log"), data = var)
PD_glmm <- glmmTMB(PD ~ Elev + Slope + Aheight + Flower + (1|Code), family = Gamma(link = "log"), data = var)
anova(PD_glm, PD_glmm)   
AIC(PD_glm, PD_glmm)


PE_glm  <- glmmTMB(PE ~ Elev + Slope + Aheight + Flower, family = Gamma(link = "log"), data = var)
PE_glmm <- glmmTMB(PE ~ Elev + Slope + Aheight + Flower + (1|Code), family = Gamma(link = "log"), data = var)
anova(PE_glm, PE_glmm)   
AIC(PE_glm, PE_glmm)


# 3.5.3 Generalized linear models versus Generalized Additive Models  ----------------------------------------------------------

model1p1 <- gam(SR ~ Elev + Slope + Aheight + Flower ,  family = poisson, data = var)
model1p2 <- gam(SR ~ s(Elev, k=3) + s(Slope, k=3) + Aheight + Flower,  family = poisson,  data = var)
summary(model1p1)
summary(model1p2)
AIC(model1p1, model1p2)
anova(model1p1, model1p2, test="Chisq")
plot(model1p2, pages = 1)
k.check(model1p2)


model2n1 <- gam(Abund ~ Elev + Slope + Aheight + Flower , family = nb(), data = var)
model2n2 <- gam(Abund ~ Elev + Slope + s(Aheight, k =4) + s(Flower, k =4), family = nb(), data = var)
summary(model2n1)
summary(model2n2)
AIC(model2n1, model2n2)
anova(model2n1, model2n2,test="Chisq" )
plot(model2n2, pages = 1)
k.check(model2n2)


model3g1 <- gam(Fric ~ Elev + Slope + Aheight + Flower, family = Gamma(link="log"), data = var)
model3g2 <- gam(Fric ~ s(Elev, k =3) + Slope + Aheight + Flower, family = Gamma(link="log"), data = var)
summary(model3g1)
summary(model3g2)
AIC(model3g1, model3g2)
anova(model3g1, model3g2 ,test="Chisq" )
plot(model3g2, pages = 1)
k.check(model3g2)


model4g1 <- gam(PD ~ Elev + Slope + Aheight + Flower , family = Gamma(link="log"), data = var)
model4g2 <- gam(PD ~ Elev + s(Slope, k =2) + s(Aheight, k =2) + Flower, family = Gamma(link="log"), data = var)
summary(model4g1)
summary(model4g2)
AIC(model4g1, model4g2)
anova(model4g1, model4g2 ,test="Chisq" )
plot(model4g2, pages = 1)
k.check(model4g2)


model5g1 <- gam(PE ~ Elev + Slope + Aheight + Flower , family = Gamma(link="log"), data = var)
model5g2 <- gam(PE ~ s(Elev, k =4) + Slope + s(Aheight, k =4) + Flower, family = Gamma(link="log"), data = var)
summary(model5g1)
summary(model5g2)
AIC(model5g1, model5g2)
anova(model5g1, model5g2 ,test="Chisq" )
plot(model5g2, pages = 1)
k.check(model5g2)


# 3.6 LASSO ---------------------------------------------------------------

# 3.6.1 Species richness --------------------------------------------------

set.seed(1233) # For reproducibility

X1 <- model.matrix(SR ~ Elev + Slope + Aheight + Flower, data = var) [,-1]
Y1 <- var[, "SR"]

# Penalty type (alpha=1 is lasso, alpha=0.5 is elastic regression, alpha=0 is the ridge)
cv.lambda.lasso1 <- cv.glmnet(x=X1, y=Y1, 
                              alpha = 1) 
plot(cv.lambda.lasso1)                        

cv.lambda.lasso1                              

# Lasso path
plot(cv.lambda.lasso1$glmnet.fit, 
     "lambda", label=FALSE)


# Extract coefficients at the lambda.min value
coef(cv.lambda.lasso1, s = "lambda.min")

# Cycle for doing 1000 cross validations and take the average of the mean error curves
MSEs <- NULL
for (i in 1:1000){
  cv <- cv.glmnet(X1, Y1, alpha= 1, family = "poisson")
  MSEs <- cbind(MSEs, cv$cvm)
}
rownames(MSEs) <- cv$lambda
lambda.min <- as.numeric(names(which.min(rowMeans(MSEs))))
lambda.min

coef(cv, s = lambda.min) 


# 3.6.2 Abundance --------------------------------------------------

set.seed(1233) # For reproducibility

X1 <- model.matrix(Abund ~ Elev + Slope + Aheight + Flower, data = var) [,-1]
Y1 <- var[, "Abund"]

# Penalty type (alpha=1 is lasso, alpha=0.5 is elastic regression, alpha=0 is the ridge)
cv.lambda.lasso1 <- cv.glmnet(x=X1, y=Y1, 
                              alpha = 1) 
plot(cv.lambda.lasso1)                        

cv.lambda.lasso1                              

# Lasso path
plot(cv.lambda.lasso1$glmnet.fit, 
     "lambda", label=FALSE)


# Extract coefficients at the lambda.min value
coef(cv.lambda.lasso1, s = "lambda.min")

# Cycle for doing 1000 cross validations and take the average of the mean error curves
MSEs <- NULL
for (i in 1:1000){
  cv <- cv.glmnet(X1, Y1, alpha= 1, family = "poisson")
  MSEs <- cbind(MSEs, cv$cvm)
}
rownames(MSEs) <- cv$lambda
lambda.min <- as.numeric(names(which.min(rowMeans(MSEs))))
lambda.min

coef(cv, s = lambda.min) 


# 3.6.3 Functional richness --------------------------------------------------

set.seed(1233) # For reproducibility

X1 <- model.matrix(Fric ~ Elev + Slope + Aheight + Flower, data = var) [,-1]
Y1 <- var[, "Fric"]

# Penalty type (alpha=1 is lasso, alpha=0.5 is elastic regression, alpha=0 is the ridge)
cv.lambda.lasso1 <- cv.glmnet(x=X1, y=Y1, 
                              alpha = 1) 
plot(cv.lambda.lasso1)                        

cv.lambda.lasso1                              

# Lasso path
plot(cv.lambda.lasso1$glmnet.fit, 
     "lambda", label=FALSE)


# Extract coefficients at the lambda.min value
coef(cv.lambda.lasso1, s = "lambda.min")

# Cycle for doing 1000 cross validations and take the average of the mean error curves
MSEs <- NULL
for (i in 1:1000){
  cv <- cv.glmnet(X1, Y1, alpha= 1, family = "gaussian")
  MSEs <- cbind(MSEs, cv$cvm)
}
rownames(MSEs) <- cv$lambda
lambda.min <- as.numeric(names(which.min(rowMeans(MSEs))))
lambda.min

coef(cv, s = lambda.min) 


# 3.6.4 Phylogenetic diversity --------------------------------------------------

set.seed(1233) # For reproducibility

X1 <- model.matrix(PD ~ Elev + Slope + Aheight + Flower, data = var) [,-1]
Y1 <- var[, "PD"]

# Penalty type (alpha=1 is lasso, alpha=0.5 is elastic regression, alpha=0 is the ridge)
cv.lambda.lasso1 <- cv.glmnet(x=X1, y=Y1, 
                              alpha = 1) 
plot(cv.lambda.lasso1)                        

cv.lambda.lasso1                              

# Lasso path
plot(cv.lambda.lasso1$glmnet.fit, 
     "lambda", label=FALSE)


# Extract coefficients at the lambda.min value
coef(cv.lambda.lasso1, s = "lambda.min")

# Cycle for doing 1000 cross validations and take the average of the mean error curves
MSEs <- NULL
for (i in 1:1000){
  cv <- cv.glmnet(X1, Y1, alpha= 1, family = "gaussian")
  MSEs <- cbind(MSEs, cv$cvm)
}
rownames(MSEs) <- cv$lambda
lambda.min <- as.numeric(names(which.min(rowMeans(MSEs))))
lambda.min

coef(cv, s = lambda.min) 


# 3.6.5 Phylogenetic endemism  --------------------------------------------------

set.seed(1233) # For reproducibility

X1 <- model.matrix(PE ~ Elev + Slope + Aheight + Flower, data = var) [,-1]
Y1 <- var[, "PE"]

# Penalty type (alpha=1 is lasso, alpha=0.5 is elastic regression, alpha=0 is the ridge)
cv.lambda.lasso1 <- cv.glmnet(x=X1, y=Y1, 
                              alpha = 1) 
plot(cv.lambda.lasso1)                        

cv.lambda.lasso1                              

# Lasso path
plot(cv.lambda.lasso1$glmnet.fit, 
     "lambda", label=FALSE)


# Extract coefficients at the lambda.min value
coef(cv.lambda.lasso1, s = "lambda.min")

# Cycle for doing 1000 cross validations and take the average of the mean error curves
MSEs <- NULL
for (i in 1:1000){
  cv <- cv.glmnet(X1, Y1, alpha= 1, family = "gaussian")
  MSEs <- cbind(MSEs, cv$cvm)
}
rownames(MSEs) <- cv$lambda
lambda.min <- as.numeric(names(which.min(rowMeans(MSEs))))
lambda.min

coef(cv, s = lambda.min) 


# 3.7 dredge --------------------------------------------------------

model1p1 <- glm(SR ~ Elev + Slope + Aheight + Flower ,  family = poisson, data = var)
model2n1 <- glm.nb(Abund ~ Elev + Slope + Aheight + Flower, data = var)
model3g1 <- glm(Fric ~ Elev + Slope + Aheight + Flower, family = Gamma(link="log"), data = var)
model4g1 <- glm(PD ~ Elev + Slope + Aheight + Flower , family = Gamma(link="log"), data = var)
model5g1 <- glm(PE ~ Elev + Slope + Aheight + Flower , family = Gamma(link="log"), data = var)

# 3.7.1  Species richness ------------------------------------------------------------------

n <- nobs(model1p1)  
fixed_effects <- coef(model1p1)
k_fixed <- length(fixed_effects)
k <- k_fixed + 1  

# Calculate the ratio n / k
ratio <- n / k

# Print results
cat("Sample size (n):", n, "\n")
cat("Number of parameters (k):", k, "\n")
cat("n / k ratio:", ratio, "\n")

# Decision
if (ratio < 40) {
  cat("You should use AICc (Corrected AIC) because n / k < 40.\n")
} else {
  cat("AIC is sufficient because n / k >= 40.\n")
}
#You should use AICc (Corrected AIC) because n / k < 40.

options(na.action = "na.fail") # Required for dredge to run
GTmodel_dredge <- dredge(model1p1, beta = F, evaluate = T, rank = AICc)
options(na.action = "na.omit") # set back to default

top_model <- get.models(GTmodel_dredge, subset = 1)[[1]]
top_model
summary(top_model)

nrow(GTmodel_dredge)
head(GTmodel_dredge)


model1p1a <- glm(SR ~ Slope + Aheight + Flower ,  family = poisson, data = var)
model1p1b <- glm(SR ~ Elev + Aheight + Flower ,  family = poisson, data = var)
model1p1c <- glm(SR ~ Elev + Slope + Aheight + Flower ,  family = poisson, data = var)
model1p1d <- glm(SR ~ Aheight + Flower ,  family = poisson, data = var)

XSR <- model.avg(GTmodel_dredge, subset = delta <= 2) 

summary(XSR)      # model-averaged coefficients + p-values
confint(XSR)      # unconditional confidence intervals
sw(XSR)   # importance of each predictor

model_performance(model1p1a)
model_performance(model1p1b)
model_performance(model1p1c)
model_performance(model1p1d)

sim_top <- simulateResiduals(top_model, n = 1000)
plot(sim_top)

testDispersion(sim_top)
testUniformity(sim_top)
testOutliers(sim_top)



# 3.7.2  Abundance  ------------------------------------------------------------------

n <- nobs(model2n1)  
fixed_effects <- coef(model2n1)
k_fixed <- length(fixed_effects)
k <- k_fixed + 1  

# Calculate the ratio n / k
ratio <- n / k

# Print results
cat("Sample size (n):", n, "\n")
cat("Number of parameters (k):", k, "\n")
cat("n / k ratio:", ratio, "\n")

# Decision
if (ratio < 40) {
  cat("You should use AICc (Corrected AIC) because n / k < 40.\n")
} else {
  cat("AIC is sufficient because n / k >= 40.\n")
}
#You should use AICc (Corrected AIC) because n / k < 40.

options(na.action = "na.fail") # Required for dredge to run
GTmodel_dredge <- dredge(model2n1, beta = F, evaluate = T, rank = AICc)
options(na.action = "na.omit") # set back to default

top_model <- get.models(GTmodel_dredge, subset = 1)[[1]]
top_model
summary(top_model)

nrow(GTmodel_dredge)
head(GTmodel_dredge)


model2n1a <- glm.nb(Abund ~ Elev  + Aheight , data = var)
model2n1b <- glm.nb(Abund ~ Aheight , data = var)
model2n1c <- glm.nb(Abund ~ Elev + Slope + Aheight , data = var)
model2n1d <- glm.nb(Abund ~ Slope + Aheight , data = var)

XA <- model.avg(GTmodel_dredge, subset = delta <= 2) 

summary(XA)      # model-averaged coefficients + p-values
confint(XA)      # unconditional confidence intervals
sw(XA)   # importance of each predictor

model_performance(model2n1a)
model_performance(model2n1b)
model_performance(model2n1c)
model_performance(model2n1d)

sim_top <- simulateResiduals(top_model, n = 1000)
plot(sim_top)

testDispersion(sim_top)
testUniformity(sim_top)
testOutliers(sim_top)


# 3.7.3  Functional richness  ------------------------------------------------------------------

n <- nobs(model3g1)  
fixed_effects <- coef(model3g1)
k_fixed <- length(fixed_effects)
k <- k_fixed + 1  

# Calculate the ratio n / k
ratio <- n / k

# Print results
cat("Sample size (n):", n, "\n")
cat("Number of parameters (k):", k, "\n")
cat("n / k ratio:", ratio, "\n")

# Decision
if (ratio < 40) {
  cat("You should use AICc (Corrected AIC) because n / k < 40.\n")
} else {
  cat("AIC is sufficient because n / k >= 40.\n")
}
#You should use AICc (Corrected AIC) because n / k < 40.

options(na.action = "na.fail") # Required for dredge to run
GTmodel_dredge <- dredge(model3g1, beta = F, evaluate = T, rank = AICc)
options(na.action = "na.omit") # set back to default

top_model <- get.models(GTmodel_dredge, subset = 1)[[1]]
top_model
summary(top_model)

nrow(GTmodel_dredge)
head(GTmodel_dredge)


model3g1a <- glm(Fric ~ Flower, family = Gamma(link="log"), data = var)
model3g1b <- glm(Fric ~ Aheight + Flower, family = Gamma(link="log"), data = var)
model3g1c <- glm(Fric ~ Elev , family = Gamma(link="log"), data = var)
model3g1d <- glm(Fric ~ Elev + Aheight, family = Gamma(link="log"), data = var)
model3g1e <- glm(Fric ~ Elev + Flower, family = Gamma(link="log"), data = var)
model3g1f <- glm(Fric ~ Aheight, family = Gamma(link="log"), data = var)

XF <- model.avg(GTmodel_dredge, subset = delta <= 2) 

summary(XF)      # model-averaged coefficients + p-values
confint(XF)      # unconditional confidence intervals
sw(XF)   # importance of each predictor

model_performance(model3g1a)
model_performance(model3g1b)
model_performance(model3g1c)
model_performance(model3g1d)
model_performance(model3g1e)
model_performance(model3g1f)

sim_top <- simulateResiduals(top_model, n = 1000)
plot(sim_top)

testDispersion(sim_top)
testUniformity(sim_top)
testOutliers(sim_top)



# 3.7.4 Phylogenetic diversity  ------------------------------------------------------------------

n <- nobs(model4g1)  
fixed_effects <- coef(model4g1)
k_fixed <- length(fixed_effects)
k <- k_fixed + 1  

# Calculate the ratio n / k
ratio <- n / k

# Print results
cat("Sample size (n):", n, "\n")
cat("Number of parameters (k):", k, "\n")
cat("n / k ratio:", ratio, "\n")

# Decision
if (ratio < 40) {
  cat("You should use AICc (Corrected AIC) because n / k < 40.\n")
} else {
  cat("AIC is sufficient because n / k >= 40.\n")
}
#You should use AICc (Corrected AIC) because n / k < 40.

options(na.action = "na.fail") # Required for dredge to run
GTmodel_dredge <- dredge(model4g1, beta = F, evaluate = T, rank = AICc)
options(na.action = "na.omit") # set back to default

top_model <- get.models(GTmodel_dredge, subset = 1)[[1]]
top_model
summary(top_model)

nrow(GTmodel_dredge)
head(GTmodel_dredge)

model4g1a <- glm(PD ~ Elev + Aheight , family = Gamma(link="log"), data = var)
model4g1b <- glm(PD ~ Elev + Slope + Aheight , family = Gamma(link="log"), data = var)
model4g1c <- glm(PD ~ Elev +  Aheight + Flower , family = Gamma(link="log"), data = var)
model4g1d <- glm(PD ~  Slope + Aheight + Flower , family = Gamma(link="log"), data = var)
model4g1e <- glm(PD ~ Aheight + Flower , family = Gamma(link="log"), data = var)


XPD <- model.avg(GTmodel_dredge, subset = delta <= 2) 

summary(XPD)      # model-averaged coefficients + p-values
confint(XPD)      # unconditional confidence intervals
sw(XPD)   # importance of each predictor

model_performance(model4g1a)
model_performance(model4g1b)
model_performance(model4g1c)
model_performance(model4g1d)
model_performance(model4g1e)


sim_top <- simulateResiduals(model4g1, n = 1000)
plot(sim_top)

testDispersion(sim_top)
testUniformity(sim_top)
testOutliers(sim_top)


# 3.7.5 Phylogenetic endemism  ------------------------------------------------------------------

n <- nobs(model5g1)  
fixed_effects <- coef(model5g1)
k_fixed <- length(fixed_effects)
k <- k_fixed + 1  

# Calculate the ratio n / k
ratio <- n / k

# Print results
cat("Sample size (n):", n, "\n")
cat("Number of parameters (k):", k, "\n")
cat("n / k ratio:", ratio, "\n")

# Decision
if (ratio < 40) {
  cat("You should use AICc (Corrected AIC) because n / k < 40.\n")
} else {
  cat("AIC is sufficient because n / k >= 40.\n")
}
#You should use AICc (Corrected AIC) because n / k < 40.

options(na.action = "na.fail") # Required for dredge to run
GTmodel_dredge <- dredge(model5g1, beta = F, evaluate = T, rank = AICc)
options(na.action = "na.omit") # set back to default

top_model <- get.models(GTmodel_dredge, subset = 1)[[1]]
top_model
summary(top_model)

nrow(GTmodel_dredge)
head(GTmodel_dredge)

model5g1a <- glm(PE ~ Aheight + Flower , family = Gamma(link="log"), data = var)
model5g1b <- glm(PE ~ Slope + Aheight + Flower , family = Gamma(link="log"), data = var)

XPE <- model.avg(GTmodel_dredge, subset = delta <= 2) 

summary(XPE)      # model-averaged coefficients + p-values
confint(XPE)      # unconditional confidence intervals
sw(XPE)   # importance of each predictor

model_performance(model5g1a)
model_performance(model5g1b)

sim_top <- simulateResiduals(model5g1, n = 1000)
plot(sim_top)

testDispersion(sim_top)
testUniformity(sim_top)
testOutliers(sim_top)


# 3.8 Final models (δAIC <=2) -------------------------------------------------

var <- as.data.frame(var)
str(var)   

model1p1a <- glm(SR ~ Slope + Aheight + Flower ,  family = poisson, data = var)
model1p1b <- glm(SR ~ Elev + Aheight + Flower ,  family = poisson, data = var)
model1p1c <- glm(SR ~ Elev + Slope + Aheight + Flower ,  family = poisson, data = var)
model1p1d <- glm(SR ~ Aheight + Flower ,  family = poisson, data = var)
model2n1a <- glm.nb(Abund ~ Elev  + Aheight , data = var)
model2n1b <- glm.nb(Abund ~ Aheight , data = var)
model2n1c <- glm.nb(Abund ~ Elev + Slope + Aheight , data = var)
model2n1d <- glm.nb(Abund ~ Slope + Aheight , data = var)
model3g1a <- glm(Fric ~ Flower, family = Gamma(link="log"), data = var)
model3g1b <- glm(Fric ~ Aheight + Flower, family = Gamma(link="log"), data = var)
model3g1c <- glm(Fric ~ Elev , family = Gamma(link="log"), data = var)
model3g1d <- glm(Fric ~ Elev + Aheight, family = Gamma(link="log"), data = var)
model3g1e <- glm(Fric ~ Elev + Flower, family = Gamma(link="log"), data = var)
model3g1f <- glm(Fric ~ Aheight, family = Gamma(link="log"), data = var)
model4g1a <- glm(PD ~ Elev + Aheight , family = Gamma(link="log"), data = var)
model4g1b <- glm(PD ~ Elev + Slope + Aheight , family = Gamma(link="log"), data = var)
model4g1c <- glm(PD ~ Elev +  Aheight + Flower , family = Gamma(link="log"), data = var)
model4g1d <- glm(PD ~  Slope + Aheight + Flower , family = Gamma(link="log"), data = var)
model4g1e <- glm(PD ~ Aheight + Flower , family = Gamma(link="log"), data = var)
model5g1a <- glm(PE ~ Aheight + Flower , family = Gamma(link="log"), data = var)
model5g1b <- glm(PE ~ Slope + Aheight + Flower , family = Gamma(link="log"), data = var)


# 3.9  McFadden pseudo-R²  ------------------------------------------------------------------
#for negative binomial
rsq.partial(model2n1a)
rsq.partial(model2n1b)
rsq.partial(model2n1c)
rsq.partial(model2n1d)

#for poisson and gamma
semi_partial_r2_glm <- function(model) {
  if (!inherits(model, "glm"))
    stop("This function currently works for 'glm' objects only.")
  
  mf   <- model.frame(model)
  fam  <- family(model)
  resp <- names(mf)[1]
  
  # all predictors (no intercept)
  terms_full <- attr(terms(model), "term.labels")
  
  # null model
  f_null     <- as.formula(paste(resp, "~ 1"))
  model_null <- glm(f_null, family = fam, data = mf)
  
  LL_null <- as.numeric(logLik(model_null))
  LL_full <- as.numeric(logLik(model))
  
  R2_full <- 1 - (LL_full / LL_null)
  
  out <- data.frame(
    model = deparse(model$call)[1],
    term = terms_full,
    sr2  = NA_real_
  )
  
  for (i in seq_along(terms_full)) {
    terms_reduced <- terms_full[-i]
    
    if (length(terms_reduced) == 0) {
      f_red <- f_null
    } else {
      f_red <- as.formula(paste(resp, "~", paste(terms_reduced, collapse = " + ")))
    }
    
    model_red <- glm(f_red, family = fam, data = mf)
    LL_red    <- as.numeric(logLik(model_red))
    R2_red    <- 1 - (LL_red / LL_null)
    
    out$sr2[i] <- R2_full - R2_red
  }
  
  attr(out, "R2_full") <- R2_full
  out
}

models_SR  <- list(model1p1a, model1p1b, model1p1c, model1p1d)
models_FRic <- list(model3g1a, model3g1b, model3g1c, model3g1d, model3g1e, model3g1f)
models_PD  <- list(model4g1a, model4g1b, model4g1c, model4g1d, model4g1e)
models_PE  <- list(model5g1a, model5g1b)

get_sr2_table <- function(model_list) {
  do.call(rbind, lapply(model_list, semi_partial_r2_glm))
}

sr2_SR   <- get_sr2_table(models_SR)
sr2_FRic <- get_sr2_table(models_FRic)
sr2_PD   <- get_sr2_table(models_PD)
sr2_PE   <- get_sr2_table(models_PE)

sr2_SR
sr2_FRic
sr2_PD
sr2_PE


# 4. many-GLM ------------------------------------------------------
#Load packages
library(mvabund) 
library(lattice)


#Load datasets
traits <- read.table("Trait_variables.csv", sep=",", header=T)
env <- read.table("Env. parameters.csv", sep=",", header=T)
abund <- read.table("Species abundance.csv", sep=",", header=T)

# Set row names for datasets
rownames(env) <- env[, 1]; env <- env[, -1]
rownames(abund) <- abund[, 1]; abund <- abund[, -1]
rownames(traits) <- traits$Species
traits <- traits[, -which(names(traits) == "Species")]
traits <- traits[, 1:10]


# 4.1 Butterfly abundance -------------------------------------------------
but_spp <- mvabund(abund)
par(mfrow = c(1, 1))
plot(but_spp)

## Draw an mvabund object in a boxplot, but using the 20 most abundant
## variables in the plot, using the square root transform, and adding
## coloured axes and title:
plot.mvabund(abund, n.vars=20, type="bx", transformation="sqrt",
             fg="lightblue", main="Solberg abundances", col.main="red")

# 4.2 Multivariate GLMs ---------------------------------------------------------------------

mod1 <- manyglm(but_spp ~ env$Elevation, family="poisson")
plot(mod1)
mod2 <- manyglm(but_spp ~ env$Elevation, family="negative_binomial")
plot(mod2)
## obtain residuals for negative binomial regression with qqplot:
resNB <- residuals(mod2)
qqnorm(resNB)
qqline(resNB,col="red")
# plot
coefplot(mod2, y.label = TRUE, incl.intercept = FALSE, cex.ylab = 0.9)
summary(mod2)


mod3 <- manyglm(but_spp ~ env$Slope, family="poisson")
plot(mod3)
mod4 <- manyglm(but_spp ~ env$Slope, family="negative_binomial")
plot(mod4)
# plot
coefplot(mod4, y.label = TRUE, incl.intercept = FALSE, cex.ylab = 0.5)
summary(mod4)


mod5 <- manyglm(but_spp ~ env$Mean.veg.height, family="poisson")
plot(mod5)
mod6 <- manyglm(but_spp ~ env$Mean.veg.height, family="negative_binomial")
plot(mod6)
coefplot(mod6,  y.label = TRUE,  incl.intercept = FALSE,  cex.ylab = 0.5,  mfrow = c(1, 1))
summary(mod6)


mod7 <- manyglm(but_spp ~ env$Flowerheads, family="poisson")
plot(mod7)
mod8 <- manyglm(but_spp ~ env$Flowerheads, family="negative_binomial")
plot(mod8)
coefplot(mod8,  y.label = TRUE,  incl.intercept = FALSE,  cex.ylab = 0.5,  mfrow = c(1, 1))
summary(mod8)


#multivariate test for the community composition as a whole
anova(mod2, nBoot=999)
anova(mod4, nBoot=999)
anova(mod6, nBoot=999)
anova(mod8, nBoot=999)

#multivariate test per species

anova(mod2, p.uni="adjusted", nBoot=999)
anova(mod4, p.uni="adjusted", nBoot=999)
anova(mod6, p.uni="adjusted", nBoot=999)
anova(mod8, p.uni="adjusted", nBoot=999)

# 4.3 Multivariate SDM ----------------------------------------------------

sdm_fit=traitglm(abund,env)
sdm_fit$fourth

#plot 
a        = max( abs(sdm_fit$fourth.corner) )
colort   = colorRampPalette(c("blue","white","red")) 
plot.spp = levelplot(t(as.matrix(sdm_fit$fourth.corner)), xlab="Environmental Variables",
                     ylab="Species", col.regions=colort(100), at=seq(-a, a, length=100),
                     scales = list( x= list(rot = 45)))
print(plot.spp)


# 5. trait-GLM ------------------------------------------------------
fit=traitglm(abund,env,traits, family = "negative.binomial")
fit$fourth
plot(fit)

#Check the overall trait by environment interaction #(17 min)
anova(fit, test ="wald", nBoot = 999) #(21 min)
anova(fit, test ="LR", nBoot = 999) #(22 min)
anova(fit, test ="score", nBoot = 999) #(3 min)

#Check the effects of individual trait by environment interactions (2-3 hours)
summary(fit, nBoot=1000)

#Plot 
a        = max( abs(fit$fourth.corner) )
colort   = colorRampPalette(c("#4F5BA6","white","#D93A3A"))  
plot.4th = levelplot(t(as.matrix(fit$fourth.corner)), xlab="Environmental Variables",
                     ylab="Species traits", col.regions=colort(100), at=seq(-a, a, length=100),
                     scales = list( x= list(rot = 45)))
print(plot.4th)

# 5.1 LASSO ---------------------------------------------------------------

ft1=traitglm(abund,env,traits, family = "negative.binomial", method="glm1path", lambda=1)
ft1$fourth 

#Plot heatmap after LASSO
a        = max( abs(ft1$fourth.corner) )
colort   = colorRampPalette(c("#D93A3A","white","#4F5BA6")) 
plot.4th = levelplot(t(as.matrix(ft1$fourth.corner)), xlab="Environmental Variables",
                     ylab="Species traits", col.regions=colort(100), at=seq(-a, a, length=100),
                     scales = list( x= list(rot = 45)))
print(plot.4th)


